/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMembersDialog: typeof import('./src/components/dashboard/teams/AddMembersDialog.vue')['default']
    AddOnPreferenceDialog: typeof import('./src/components/AddOnPreferenceDialog.vue')['default']
    AddVenueDialog: typeof import('./src/components/dashboard/events/AddVenueDialog.vue')['default']
    AttendeeFormControl: typeof import('./src/components/AttendeeFormControl.vue')['default']
    BackButton: typeof import('./src/components/common/BackButton.vue')['default']
    BaseCustomEventForm: typeof import('./src/components/BaseCustomEventForm.vue')['default']
    BillingDetails: typeof import('./src/components/BillingDetails.vue')['default']
    BookingEventInfo: typeof import('./src/components/BookingEventInfo.vue')['default']
    BookingFinancialSummary: typeof import('./src/components/BookingFinancialSummary.vue')['default']
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingHeader: typeof import('./src/components/BookingHeader.vue')['default']
    BookingSummary: typeof import('./src/components/BookingSummary.vue')['default']
    BuzzLogo: typeof import('./src/components/common/BuzzLogo.vue')['default']
    CancellationRequestDialog: typeof import('./src/components/CancellationRequestDialog.vue')['default']
    CancellationRequestNotice: typeof import('./src/components/CancellationRequestNotice.vue')['default']
    CustomFieldInput: typeof import('./src/components/CustomFieldInput.vue')['default']
    CustomFieldsSection: typeof import('./src/components/CustomFieldsSection.vue')['default']
    Drawer: typeof import('./src/components/common/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./src/components/common/drawer/DrawerContent.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    EventBanner: typeof import('./src/components/dashboard/events/EventBanner.vue')['default']
    EventBookings: typeof import('./src/components/dashboard/events/EventBookings.vue')['default']
    EventCard: typeof import('./src/components/dashboard/events/EventCard.vue')['default']
    EventDetailsHeader: typeof import('./src/components/EventDetailsHeader.vue')['default']
    EventDrawer: typeof import('./src/components/dashboard/events/EventDrawer.vue')['default']
    EventGuestItem: typeof import('./src/components/dashboard/events/EventGuestItem.vue')['default']
    EventLocation: typeof import('./src/components/dashboard/events/EventLocation.vue')['default']
    EventMedium: typeof import('./src/components/dashboard/events/EventMedium.vue')['default']
    EventPageHeader: typeof import('./src/components/dashboard/events/EventPageHeader.vue')['default']
    EventRoute: typeof import('./src/components/dashboard/events/EventRoute.vue')['default']
    EventSchedule: typeof import('./src/components/dashboard/events/EventSchedule.vue')['default']
    EventSelector: typeof import('./src/components/EventSelector.vue')['default']
    FilterBar: typeof import('./src/components/common/filters/FilterBar.vue')['default']
    FormFieldSections: typeof import('./src/components/FormFieldSections.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    LoginRequired: typeof import('./src/components/LoginRequired.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OfflinePaymentDialog: typeof import('./src/components/OfflinePaymentDialog.vue')['default']
    PaymentGatewayDialog: typeof import('./src/components/PaymentGatewayDialog.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
    PrintedTicket: typeof import('./src/components/dashboard/tickets/PrintedTicket.vue')['default']
    ProfileView: typeof import('./src/components/ProfileView.vue')['default']
    ProposalCard: typeof import('./src/components/dashboard/proposals/ProposalCard.vue')['default']
    ProposalEditDialog: typeof import('./src/components/ProposalEditDialog.vue')['default']
    QRCodeExpandDialog: typeof import('./src/components/QRCodeExpandDialog.vue')['default']
    QRScanner: typeof import('./src/components/QRScanner.vue')['default']
    RestrictionNotices: typeof import('./src/components/RestrictionNotices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SponsorshipPaymentDialog: typeof import('./src/components/SponsorshipPaymentDialog.vue')['default']
    SuccessMessage: typeof import('./src/components/SuccessMessage.vue')['default']
    TeamHero: typeof import('./src/components/dashboard/teams/TeamHero.vue')['default']
    TeamPageHeader: typeof import('./src/components/dashboard/teams/TeamPageHeader.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard.vue')['default']
    TicketDetailsModal: typeof import('./src/components/TicketDetailsModal.vue')['default']
    TicketsSection: typeof import('./src/components/TicketsSection.vue')['default']
    TicketTransferDialog: typeof import('./src/components/TicketTransferDialog.vue')['default']
    TimelineList: typeof import('./src/components/dashboard/TimelineList.vue')['default']
    TransferTicketDialog: typeof import('./src/components/TransferTicketDialog.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
}
